### ISSUE TITLE
RShiny: Regulatory apps - Update titles to also include "Administrative"  

### ISSUE THREAD

**Issue by amabdallah** [WSWCWaterDataExchange/WaDE2.0Apps#20]
Let's update the titles to also include "Administrative"  
**Regulatory and Administrative Overlays** 

![image](https://github.com/WSWCWaterDataExchange/WaDE2.0Apps/assets/3268971/9f7fb879-a107-43a1-9cd4-7b0f4dcc6e2e)

![image](https://github.com/WSWCWaterDataExchange/WaDE2.0Apps/assets/3268971/8ed53eb0-33db-4837-8341-1b05436b921c)

**Comment by rwjam** [comment]
changed dashboardHeader title and dashboardBody title to 'Regulatory and Administrative Overlays'



![Image](https://github.com/WSWCWaterDataExchange/WaDE2.0Apps/assets/17555073/36977832-02d3-4820-bda4-d83365e1c7a8)
